[package]
name = "trade"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
spl-token = "4.0"
borsh = "0.10.3"
solana-program = "1.16" 

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]