[package]
name = "offer"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
borsh = { workspace = true }
solana-program = "1.16" 

[features]
idl-build = ["anchor-lang/idl-build"]