[features]
seeds = false
skip-lint = false

[programs.localnet]
price = "96qmPcTg1LHUK79c76rVVxGKjpGq1UtDpJx4ca3mdTa2"
offer = "84veR3Kq5jLFCrmgYTSWSyH2RcHYMDVY75EBrqJochp4"
trade = "EthW3z9S7GB6nSLtqCPdmqcQmpAPVFys2enbG9LVRTwo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "target/deploy/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/price",
  "programs/offer",
  "programs/trade"
]

[workspace.metadata.program-sizes]
price = 1024000
offer = 1024000
trade = 1024000

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[toolchain]
anchor_version = "0.29.0" 