[features]
seeds = false
skip-lint = false

[programs.localnet]
price = "98Cz1djtXYRfcRUq1gf9GKhjrS7nfdP3AHzoP9PCujD8"
offer = "6K5JnHicvejLWv4uTHPNSvcHRcmUWXMqrvHa6DqYQUU4"
trade = "7VwNNAQsWceNCTiVaDaL7X7HL1ujN5RCha24DEJVRsQ3"

[programs.mainnet]
price = "YNFm4bfV6Zui5KrEu4JAZAex8wcyXDAcQQeKPCk2vHu"
offer = "5uzvhpisZmWcZMNvNwNkGpDUbkYqLfZNcG2zxLmGgRgh"
trade = "9S8i1BpwEW88Zn7uW28eBdYmw2C6EYwz1BHBoeZFkPCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "target/deploy/test-keypair.json"

[scripts]
test = "cd tests && pnpm test:offer"

[workspace]
types = "target/types"
members = [
  "programs/price",
  "programs/offer",
  "programs/trade"
]

[workspace.metadata.program-sizes]
price = 2097152
offer = 1048576
trade = 2097152

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"
commitment = "processed"

[toolchain]
anchor_version = "0.29.0" 