[features]
seeds = false
skip-lint = false

[programs.localnet]
hub = "9iWg8Fhoh9Z5zo9rhgD3Z2FS46ggUwRnRwdKHtB92w74"
trade = "ENJvkqkwjEKd2CPd9NgcwEywx6ia3tCrvHE1ReZGac8t"
offer = "Gpy5ATEJY5YawGqJhBd1Xcd59NZW547tCjH9d8s2B1vp"
price = "5XkzWi5XrzgZGTw6YAYm4brCsRTYGCZpNiZJkMWwWUx5"
profile = "CfC3efU4b5ppjSBYJwiKrZtz3hmzBBgSM2s6RCFN4nYA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.1" 