[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
offer = "FSnCsffRYjRwbpzFCkbwSFtgfSNbxrpYUsq84opqG4wW"
price = "BGuwRibtPCCLCo98AFDk6C3QUPS2VHBkTRyDgkCrySfG"
profile = "8FJf3ymGwZ2ctUP85QRCsE2kMcuQY5Eu7X3dyXr7XakD"
trade = "6VXLHER2xPndomqaXWPPUH3733HVmcRMUuU5w9eNVqbZ"

[programs.mainnet]
offer = "FSnCsffRYjRwbpzFCkbwSFtgfSNbxrpYUsq84opqG4wW"
price = "BGuwRibtPCCLCo98AFDk6C3QUPS2VHBkTRyDgkCrySfG"
profile = "8FJf3ymGwZ2ctUP85QRCsE2kMcuQY5Eu7X3dyXr7XakD"
trade = "2ebQZghoJAExZ64eUuw5xq7GVycibtsyA2yPKgfNSYNj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "target/deploy/test-keypair.json"

[workspace]
members = ["programs/price", "programs/offer", "programs/trade", "programs/profile"]
types = "target/types"

[scripts]
test = "cd tests && pnpm test:offer"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
